### ISSUE TITLE
Two installation problems

### ISSUE THREAD

**Issue by oliverschmidt** [KrisKennaway/ii-pix#3]
Hi Kris,

Running the command

```
python precompute_conversion.py
```

with Python 3.10 on Windows gave me

1.

```
ModuleNotFoundError: No module named 'networkx'
```

https://www.colour-science.org/installation-guide/ describes `networkx` as optional dependency. So it seems `networkx` needs to be added to the dependencies in your README. I "fixed" that issue by installing `networkx`. Then the same command gave me

2.

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/rgb_to_cam16ucs.npy'
```
Just as a wild guess I manually created a directory `data` - and voilà - it worked like a charm. It would be great if you could either have that directory created automatically or add it to the installation commands in your README.

Thanks in advance, Oliver

**Comment by KrisKennaway** [comment]
Thanks for the bug report, and sorry I missed this - my github notifications were disabled for some reason :(

1) was fixed a while back, there's now a `requirements.txt` that should cover installing dependencies (`pip install -r requirements.txt`.  Installation instructions have also been updated.

2) I'll fix this one shortly

**Comment by oliverschmidt** [comment]
Thanks :-)
